In [31]:
import random
import torch

In [ ]:
from transformers import pipeline, set_seed
set_seed(55)
generator = pipeline('text-generation', model='models\pretrained_models\WenZhong2.0-GPT2-3.5B-chinese',device=0)
generator("我是一个外卖小哥，我的工作是", max_length=100, num_return_sequences=1)

In [5]:
import sys
print(sys.path[0])

e:\Code\ljj_person_project\AI-Tamer\NLP\text_generation


In [15]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
tokenizer = GPT2Tokenizer.from_pretrained(r'..\..\pretrained_models\nlp\WenZhong2.0-GPT2-3.5B-chinese')
model = GPT2LMHeadModel.from_pretrained(r'..\..\pretrained_models\nlp\WenZhong2.0-GPT2-3.5B-chinese').to('cuda')

In [3]:
# 从output预测中随机选择概率最大的前1个单词(这个前几个单词根据模型的性能来定，这个模型只能是1)
def random_choice(preds, top_n=1):
    x = random.choice(preds[0][-1,:].sort(descending=True)[1][:top_n])
    return x.item()

max_length = 100
context = "我是一个外卖小哥，我的工作是"
input_ids = tokenizer.encode(context)
for _ in range(max_length):
    output = model(torch.tensor(input_ids).to('cuda'))
    predicted = random_choice(output)
    if predicted == 50256:
        print('遇到中止符')
        break
    input_ids = input_ids + [predicted]
print(tokenizer.decode(input_ids))



我是一个外卖小哥，我的工作是每天早上5点半起床，然后把外卖送到楼下，然后再把楼下的顾客送到楼上，每天工作时间是8个小时，每


In [12]:
text = '你好'
input_ids = tokenizer(text, return_tensors='pt')

In [13]:
input_ids

{'input_ids': tensor([[19526,   254, 25001,   121]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [16]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50304, 3072)
    (wpe): Embedding(1024, 3072)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-29): 30 x GPT2Block(
        (ln_1): LayerNorm((3072,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((3072,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): FastGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((3072,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=3072, out_features=50304, bias=False)
)

# Flan-T5

In [1]:
# pip install accelerate
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained(r"../../pretrained_models/nlp/flan-t5-base")
model = T5ForConditionalGeneration.from_pretrained(r"../../pretrained_models/nlp/flan-t5-base", device_map="auto")


d:\softwares\professional\Anaconda3\envs\torch_cuda118\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
input_text = "translate English to German: How old are you?"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("cuda")
print(input_ids)
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))

tensor([[13959,  1566,    12,  2968,    10,   571,   625,    33,    25,    58,
             1]], device='cuda:0')


d:\softwares\professional\Anaconda3\envs\torch_cuda118\lib\site-packages\transformers\generation\utils.py:1288: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


<pad> Wie old sind Sie?</s>


In [3]:
text = 'translate Chinese to English: 你好'
input_ids = tokenizer(text, return_tensors='pt').input_ids.to("cuda")
print(input_ids)
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))

tensor([[13959,  2830,    12,  1566,    10,     3,     2,     1]],
       device='cuda:0')
<pad> <unk></s>


d:\softwares\professional\Anaconda3\envs\torch_cuda118\lib\site-packages\transformers\generation\utils.py:1288: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


# mt5-base

In [11]:
from transformers import MT5Tokenizer, MT5ForConditionalGeneration

tokenizer = MT5Tokenizer.from_pretrained(r"../../pretrained_models/nlp/mt5-base")
model = MT5ForConditionalGeneration.from_pretrained(r"../../pretrained_models/nlp/mt5-base", device_map="auto")

In [20]:

input_text = "summarize: studies have shown that owning a dog is good for you"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("cuda")

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

<extra_id_0>, a dog.


In [2]:
input_text = "你好啊"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids


tensor([[  259,  4235,  3586, 33332,     1]])

In [4]:
input_ids

tensor([[  259,  4235,  3586, 33332,     1]])

In [5]:
tokenizer.decode(input_ids[0])

'你好啊</s>'

In [39]:

t = "类型#裤*版型#宽松*风格#性感*图案#线条*裤型#阔腿裤"
x = tokenizer(t, return_tensors="pt")
x


{'input_ids': tensor([[   259, 102690,    717, 131389,    894,   4965,   4851,    717,  57987,
          12150,    894, 118181,    717, 198083,    894,   5579,  14952,    717,
           8618,  11587,    894, 131389,   4851,    717, 157454,  87917, 131389,
              1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]])}

In [53]:
x['input_ids'].numel()

28

In [1]:
import torch
from torch import nn

In [9]:
m = nn.LogSoftmax(dim=1)
k = nn.Softmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
print(input)
# each element in target has to have 0 <= value < C  
target = torch.tensor([1, 0, 4])
print(target)
print(m(input))
print(k())
output = loss(m(input), target) 
print(output) 
output.backward()

tensor([[-0.8537, -1.0618, -0.4314, -1.7325, -1.1694],
        [ 1.2923, -0.4685,  0.2874,  0.4401,  1.1569],
        [ 0.3588, -0.7489,  0.5370, -0.8795,  0.2240]], requires_grad=True)
tensor([1, 0, 4])
tensor([[-1.5001, -1.7082, -1.0778, -2.3789, -1.8158],
        [-1.0430, -2.8038, -2.0480, -1.8953, -1.1784],
        [-1.3054, -2.4131, -1.1272, -2.5437, -1.4402]],
       grad_fn=<LogSoftmaxBackward0>)
tensor([[0.2231, 0.1812, 0.3403, 0.0927, 0.1627],
        [0.3524, 0.0606, 0.1290, 0.1503, 0.3078],
        [0.2711, 0.0895, 0.3239, 0.0786, 0.2369]], grad_fn=<SoftmaxBackward0>)
tensor(1.3971, grad_fn=<NllLossBackward0>)


In [4]:
import evaluate

d:\softwares\professional\Anaconda3\envs\torch_cuda118\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
blue = evaluate.load('bleu')

Using the latest cached version of the module from C:\Users\SeungHee\.cache\huggingface\modules\evaluate_modules\metrics\evaluate-metric--bleu\9e0985c1200e367cce45605ce0ecb5ede079894e0f24f54613fca08eeb8aff76 (last modified on Fri Jun 23 22:41:26 2023) since it couldn't be found locally at evaluate-metric--bleu, or remotely on the Hugging Face Hub.


In [26]:
pred = "这款衬衫采用宽松的版型设计,穿着舒适又不挑身材。圆领设计,修饰颈部线条,修饰颈部线条。宽松的版型设计,穿着舒适又不挑身材。宽松的版型,遮肉显瘦。"
label = "穿着舒适又不挑身材。圆领设计,修饰颈部线条,修饰颈部线条。宽松的版型设计,穿着舒适又不挑身材。宽松的版型,遮肉显瘦。"


In [27]:
blue.compute(predictions=[pred], references=[label])

{'bleu': 0.7860753021519787,
 'precisions': [0.8181818181818182, 0.8, 0.7777777777777778, 0.75],
 'brevity_penalty': 1.0,
 'length_ratio': 1.2222222222222223,
 'translation_length': 11,
 'reference_length': 9}

In [18]:
from jieba import lcut

lcut("这款衬衫采用宽松的版型设计,穿着舒适又不挑身材。圆领设计,修饰颈部线条,修饰颈部线条。宽松的版型设计,穿着舒适又不挑身材。宽松的版型,遮肉显瘦。")

['这',
 '款',
 '衬衫',
 '采用',
 '宽松',
 '的',
 '版型',
 '设计',
 ',',
 '穿着',
 '舒适',
 '又',
 '不',
 '挑',
 '身材',
 '。',
 '圆领',
 '设计',
 ',',
 '修饰',
 '颈部',
 '线条',
 ',',
 '修饰',
 '颈部',
 '线条',
 '。',
 '宽松',
 '的',
 '版型',
 '设计',
 ',',
 '穿着',
 '舒适',
 '又',
 '不',
 '挑',
 '身材',
 '。',
 '宽松',
 '的',
 '版型',
 ',',
 '遮肉',
 '显瘦',
 '。']

In [16]:
predictions = ["这款衬衫采用宽松的版型设计,穿着舒适又不挑身材。圆领设计,修饰颈部线条,修饰颈部线条。宽松的版型设计,穿着舒适又不挑身材。宽松的版型,遮肉显瘦。",
               "这款连衣裙选用优质的网纱面料制作而成,手感柔软舒适,穿着舒适透气,穿着舒适透气。高贵优雅的圆领设计,修饰颈部线条,修饰颈部线条。收腰的版型设计,修饰颈部线条,修饰颈部线条。", 
               "简约大方的阔腿裤,简约大方的直筒版型,修饰腿部线条,修饰腿部线条。宽松的阔腿裤型,修饰腿部线条,修饰腿部线条。宽松的阔腿裤型,修饰腿部线条。宽松的阔腿裤型,修饰腿部线条。",
               "这款西装外套采用了蕾丝拼接的面料制作而成,穿着舒适透气,穿着舒适透气。拼接的蕾丝面料,穿着舒适透气。拼接的蕾丝面料,穿着舒适透气,穿着舒适。"]
references = [
     "萌趣印花点缀整体衣身，元气满满的衬衫让你在春天活力四射。气质的小半圆领设计，巧妙的勾勒你的脖颈线条，在视觉上增添高挑出众的气质。略微宽松的款式设计，巧妙的遮住你的肉肉，形成修长的线条美感，营造一身高级的慵懒感。不对称下摆的设计，增添了整体造型的层次感，巧妙的展现你独特的个性与魅力。",
     "透露着清新淡雅，高贵知性，端庄的气质连衣裙，适合每个美眉。它经典的圆领设计，修饰了女性细长的脖颈。腰身处收腰的裁剪，不仅拉伸身材比例，更凸显了高挑的身姿。网纱刺绣的设计，把女性的高贵端庄，典雅知性气质展现的淋漓精致。",
     "简约大方，时尚休闲，宽松直筒阔腿裤的版型设计简约却不简单，使得行走间自带清风，随性洒脱的魅力令人无法抵挡，同时，彰显出英姿飒爽的女王范儿。结合立体感的菱形提花面料，使得这条阔腿裤富有肌理感，低调而不失奢华地诠释着精致魅力。",
     "春暖花开，万物复苏。又到了西装发挥作用的时候，西服的硬朗是不可磨灭的。这款袖口蕾丝的皮西装，中和了中性的感觉，在帅气与女人之间随意切换，肌理感pu皮面料。袖口与拼接蕾丝可脱卸，复古风十足~",
]

results = blue.compute(predictions=predictions, references=references, tokenizer=lcut)
print(results)

{'bleu': 0.0, 'precisions': [0.31088082901554404, 0.047619047619047616, 0.010810810810810811, 0.0], 'brevity_penalty': 0.6338401097192047, 'length_ratio': 0.6868327402135231, 'translation_length': 193, 'reference_length': 281}


In [8]:
results

{'bleu': 0.0,
 'precisions': [0.31088082901554404,
  0.047619047619047616,
  0.010810810810810811,
  0.0],
 'brevity_penalty': 0.6338401097192047,
 'length_ratio': 0.6868327402135231,
 'translation_length': 193,
 'reference_length': 281}

In [25]:

for pre, label in zip(predictions, references):
    print(pre)
    print(label)
    print(blue.compute(predictions=[pre], references=[label],tokenizer=lcut))
    break

这款衬衫采用宽松的版型设计,穿着舒适又不挑身材。圆领设计,修饰颈部线条,修饰颈部线条。宽松的版型设计,穿着舒适又不挑身材。宽松的版型,遮肉显瘦。
萌趣印花点缀整体衣身，元气满满的衬衫让你在春天活力四射。气质的小半圆领设计，巧妙的勾勒你的脖颈线条，在视觉上增添高挑出众的气质。略微宽松的款式设计，巧妙的遮住你的肉肉，形成修长的线条美感，营造一身高级的慵懒感。不对称下摆的设计，增添了整体造型的层次感，巧妙的展现你独特的个性与魅力。
{'bleu': 0.0, 'precisions': [0.34782608695652173, 0.044444444444444446, 0.0, 0.0], 'brevity_penalty': 0.4101204639912304, 'length_ratio': 0.5287356321839081, 'translation_length': 46, 'reference_length': 87}


In [22]:
from nltk.tokenize import word_tokenize

word_tokenize("asdasdasdsa asdas")

['asdasdasdsa', 'asdas']

In [30]:
predictions = ["这款 衬衫 采用 宽松 的 版型 设计"]
references = [
     "这款 衬衫 采用 宽松 的 版型"
]
results = blue.compute(predictions=predictions, references=references)
results

ValueError: Predictions and/or references don't match the expected format.
Expected format:
Feature option 0: {'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}
Feature option 1: {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')},
Input predictions: ['这款', '衬衫'],
Input references: ['这款', '衬衫']